<a href="https://colab.research.google.com/github/mohanmarimuthu1/Test.txt/blob/main/dotProject1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as pt
import seaborn as sns
import pandas as pd
%matplotlib inline

In [4]:
columns = ["sepal_length","sepal_width","petal_length","petal_width","class_labels"]

In [7]:
#loading data
df = pd.read_csv("/content/iris.data",names=columns)
print(df)
df.head()
#sep features and targest
data = df.values
x = data[:,0:4]
y = data[:,4]

     sepal_length  sepal_width  petal_length  petal_width    class_labels
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [8]:
print(x)
print(y)
#calculate avg
y_data = np.array([np.average(x[:,i][y==j].astype("float32"))for i in range(x.shape[1]) for j in (np.unique(y))])
y_data_reshaped = y_data.reshape(4,3)
y_data_reshaped = np.swapaxes(y_data_reshaped,0,1)
x_axis = np.arange(len(columns)-1)
width = 0.25


[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.0 3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.0 1.4 0.1]
 [4.3 3.0 1.1 0.1]
 [5.8 4.0 1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.0 0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.0 3.0 1.6 0.2]
 [5.0 3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.0 3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.0 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.0 3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.0 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.0 3.3 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [9]:
#split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [10]:
print(x_train)

[[5.0 3.5 1.3 0.3]
 [6.0 3.0 4.8 1.8]
 [5.1 3.5 1.4 0.3]
 [5.6 2.8 4.9 2.0]
 [6.1 2.9 4.7 1.4]
 [5.7 2.8 4.5 1.3]
 [4.4 3.2 1.3 0.2]
 [5.0 3.3 1.4 0.2]
 [6.3 3.3 6.0 2.5]
 [6.5 2.8 4.6 1.5]
 [6.9 3.2 5.7 2.3]
 [6.4 2.7 5.3 1.9]
 [5.1 3.3 1.7 0.5]
 [6.7 3.1 4.7 1.5]
 [5.5 4.2 1.4 0.2]
 [5.1 3.4 1.5 0.2]
 [4.6 3.1 1.5 0.2]
 [4.8 3.4 1.9 0.2]
 [6.3 3.4 5.6 2.4]
 [6.3 2.8 5.1 1.5]
 [6.7 3.3 5.7 2.1]
 [5.7 2.9 4.2 1.3]
 [5.8 2.7 4.1 1.0]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1.0]
 [6.7 3.0 5.0 1.7]
 [5.3 3.7 1.5 0.2]
 [6.8 3.2 5.9 2.3]
 [6.5 3.0 5.2 2.0]
 [5.6 3.0 4.1 1.3]
 [6.5 3.2 5.1 2.0]
 [5.2 3.4 1.4 0.2]
 [7.7 3.8 6.7 2.2]
 [6.0 2.2 4.0 1.0]
 [6.7 3.0 5.2 2.3]
 [7.9 3.8 6.4 2.0]
 [7.7 2.8 6.7 2.0]
 [5.1 3.8 1.6 0.2]
 [5.1 3.5 1.4 0.2]
 [5.4 3.7 1.5 0.2]
 [6.6 3.0 4.4 1.4]
 [5.2 3.5 1.5 0.2]
 [6.7 3.1 5.6 2.4]
 [7.7 3.0 6.1 2.3]
 [5.1 3.7 1.5 0.4]
 [5.8 2.7 3.9 1.2]
 [5.5 2.3 4.0 1.3]
 [4.3 3.0 1.1 0.1]
 [5.7 3.8 1.7 0.3]
 [5.6 2.7 4.2 1.3]
 [4.4 2.9 1.4 0.2]
 [7.0 3.2 4.7 1.4]
 [5.7 2.8 4.

In [11]:
print(y_train)

['Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virgini

In [12]:
print(x_test)

[[6.5 3.0 5.5 1.8]
 [6.9 3.1 5.1 2.3]
 [6.1 3.0 4.6 1.4]
 [4.5 2.3 1.3 0.3]
 [4.6 3.2 1.4 0.2]
 [6.2 2.8 4.8 1.8]
 [6.1 2.8 4.7 1.2]
 [5.8 2.8 5.1 2.4]
 [4.8 3.1 1.6 0.2]
 [5.0 2.3 3.3 1.0]
 [5.8 2.7 5.1 1.9]
 [6.4 3.2 4.5 1.5]
 [6.7 3.1 4.4 1.4]
 [7.3 2.9 6.3 1.8]
 [5.1 2.5 3.0 1.1]
 [5.0 3.5 1.6 0.6]
 [6.4 3.2 5.3 2.3]
 [6.4 2.9 4.3 1.3]
 [6.3 2.5 5.0 1.9]
 [7.2 3.6 6.1 2.5]
 [6.2 2.9 4.3 1.3]
 [6.4 3.1 5.5 1.8]
 [5.5 2.6 4.4 1.2]
 [4.8 3.0 1.4 0.1]
 [5.9 3.2 4.8 1.8]
 [5.4 3.9 1.7 0.4]
 [4.9 3.1 1.5 0.1]
 [6.1 3.0 4.9 1.8]
 [4.7 3.2 1.6 0.2]
 [6.0 2.9 4.5 1.5]]


In [13]:
print(y_test)

['Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-versicolor']


In [14]:
#svm
from sklearn.svm import SVC
svn = SVC()
svn.fit(x_train,y_train)

SVC()

In [15]:
#prediction
predictions = svn.predict(x_test)

In [16]:
#calculate accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,predictions)

0.9666666666666667

In [17]:
#class report
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.92      1.00      0.96        11
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [22]:
x_new = np.array([[3,2,1,0.2]])
predictions = svn.predict(x_new)
print("prediction of species:{}".format(predictions))


prediction of species:['Iris-setosa']
